### ISSUE TITLE
你好，请问能都增加一个Title_case(首字母大写)

### ISSUE THREAD

**Issue by heartacker** [qq444716720/vscode-convert-utils#1]
你好，这是一个非常好用的插件，不知道能否增加一个titlecase
比如单词convert
支持convert-->CONVERT-->Convert
非常感谢，有时候还是需要这种首字母大写的

**Comment by zxpzdtom** [comment]
![image](https://github.com/zxpzdtom/vscode-convert-utils/assets/22407004/6f9a8745-d76e-4305-bd40-4eb80aa30be8)

抱歉，才看到你得消息，这个能力是支持的哈
